function preload() {
    const imagesList = [
                   "./img/wave.jpg",
                       "./img/wild.jpg",
                     "./img/heat.jpg"];

    const images = [];
    for (let i = 0; i < imagesList.length; i++) {
        images[i] = new Image();
        images[i].src = imagesList[i];
    }

    console.log('Images preloaded : \n\t ${images[0].src} \n\t ${images[1].src} \n\t ${images[2].src}');
};

window.addEventListener("load", preload);

var btnlist = document.querySelectorAll("button");

var obj = {
    wave: {
        headingcont:'wave',
        bodytxt: "Wave power is the capture of energy of wind waves to do useful work – for example, electricity generation, water desalination, or pumping water. A machine that exploits wave power is a wave energy converter (WEC)Wave power is distinct from tidal power, which captures the energy of the current caused by the gravitational pull of the Sun and Moon. Waves and tides are also distinct from ocean currents which are caused by other forces including breaking waves, wind, the Coriolis effect, cabbeling, and differences in temperature and salinity.Wave-power generation is not a widely employed commercial technology, although there have been attempts to use it since at least 1890.In 2000 the worlds first commercial Wave Power Device, the Islay LIMPET was installed on the coast of Islay in Scotland and connected to the National Grid[2]. In 2008, the first experimental multi-generator wave farm was opened in Portugal at the Aguçadoura Wave Park.Waves are generated by wind passing over the surface of the sea. As long as the waves propagate slower than the wind speed just above the waves, there is an energy transfer from the wind to the waves. Both air pressure differences between the upwind and the lee side of a wave crest, as well as friction on the water surface by the wind, making the water to go into the shear stress causes the growth of the wavesWave height is determined by wind speed, the duration of time the wind has been blowing, fetch (the distance over which the wind excites the waves) and by the depth and topography of the seafloor (which can focus or disperse the energy of the waves). A given wind speed has a matching practical limit over which time or distance will not produce larger waves. When this limit has been reached the sea is said to be fully developed.",
        imgurl: './img/wave.jpg',
        imgAlt: 'wave'
    },
    wind: {
        headingcont: 'wind',
        bodytxt: "Wind power is the use of air flow through wind turbines to provide the mechanical power to turn electric generators. Wind power, as an alternative to burning fossil fuels, is plentiful, renewable, widely distributed, clean, produces no greenhouse gas emissions during operation, consumes no water, and uses little land.[2] The net effects on the environment are far less problematic than those of nonrenewable power sourcesWind farms consist of many individual wind turbines, which are connected to the electric power transmission network. Onshore wind is an inexpensive source of electric power, competitive with or in many places cheaper than coal or gas plants.Offshore wind is steadier and stronger than on land and offshore farms have less visual impact, but construction and maintenance costs are considerably higher. Small onshore wind farms can feed some energy into the grid or provide electric power to isolated off-grid locations Wind power gives variable power, which is very consistent from year to year but has significant variation over shorter time scales. It is therefore used in conjunction with other electric power sources to give a reliable supply. As the proportion of wind power in a region increases, a need to upgrade the grid and a lowered ability to supplant conventional production can occur.[7][8] Power-management techniques such as having excess capacity, geographically distributed turbines, dispatchable backing sources, sufficient hydroelectric power, exporting and importing power to neighboring areas, or reducing demand when wind production is low, can in many cases overcome these problems.[9][10] In addition, weather forecasting permits the electric-power network to be readied for the predictable variations in production that occur.",
        imgurl: './img/wind.jpg',
        imgAlt: 'wind'
    },
    heat: {
        headingcont: 'heat',
        bodytxt: "Geothermal energy is thermal energy generated and stored in the Earth. Thermal energy is the energy that determines the temperature of matter. The geothermal energy of the Earth's crust originates from the original formation of the planet and from radioactive decay of materials (in currently uncertain[1] but possibly roughly equal proportions). The geothermal gradient, which is the difference in temperature between the core of the planet and its surface, drives a continuous conduction of thermal energy in the form of heat from the core to the surface. The adjective geothermal originates from the Greek roots, meaning earth,thermos meaning hot Earth's internal heat is thermal energy generated from radioactive decay and continual heat loss from Earth's formation.[3] Temperatures at the core–mantle boundary may reach over 4000 °C (7,200 °F).[4] The high temperature and pressure in Earth's interior cause some rock to melt and solid mantle to behave plastically, resulting in portions of the mantle convecting upward since it is lighter than the surrounding rock. Rock and water is heated in the crust, sometimes up to 370 °C (700 °F) With water from hot springs, geothermal energy has been used for bathing since Paleolithic times and for space heating since ancient Roman times, but it is now better known for electricity generation. Worldwide, 11,700 megawatts (MW) of geothermal power was available in 2013.[6] An additional 28 gigawatts of direct geothermal heating capacity is installed for district heating, space heating, spas, industrial processes, desalination and agricultural applications as of 2010.Geothermal power is cost-effective, reliable, sustainable, and environmentally friendly,[8] but has historically been limited to areas near tectonic plate boundaries. Recent technological advances have dramatically expanded the range and size of viable resources, especially for applications such as home heating, opening a potential for widespread exploitation. Geothermal wells release greenhouse gases trapped deep within the earth, but these emissions are much lower per energy unit than those of fossil fuels.",
        imgurl: './img/heat.jpg',
        imgAlt: 'heat'
    },
}

var ref = document.getElementsByClassName("content");

btnlist[0].setAttribute("id", "active");

ref[0].innerHTML = `<h1>${obj.wave.headingcont}</h1>
                      <img src ="${obj.wave.imgurl}" alt="${obj.wave.imgAlt}" style="width:350px; height:350px;">;
                      <p>${obj.wave.bodytxt}</p>`;

function contenthandler(e) {
    for (let i = 0; i < btnlist.length; i++) {
        if (btnlist[i].hasAttribute("id")) {
            btnlist[i].removeAttribute("id");
        }
    }

    e.target.setAttribute("id", "active");
    /*
       Use the element-object method setAttribute() to set the id active-button
       to the currently clicked button. */


    for (let i = 0; i < btnlist.length; i++) {
        if (btnlist[i].hasAttribute("id")) {
            if (i == 0) {
                ref[0].innerHTML = `<h1>${obj.wave.headingcont}</h1>
                              <img src ="${obj.wave.imgurl}" alt="${obj.wave.imgAlt}">;
                              <p>${obj.wave.bodytxt}</p>`;
            }
            if (i == 1) {
                ref[0].innerHTML = `<h1>${obj.wind.headingcont}</h1>
                              <img src ="${obj.wind.imgurl}" alt="${obj.wind.imgAlt}" >;
                              <p>${obj.wind.bodytxt}</p>`;
            }
            if (i == 2) {
                ref[0].innerHTML = `<h1>${obj.heat.headingcont}</h1>
                              <img src ="${obj.heat.imgurl}" alt="${obj.heat.imgAlt}" >;
                              <p>${obj.heat.bodytxt}</p>`;
            }
        }
    }

    /*
    Use conditional and event-object to check which button is clicked
    and based on that, create HTML with the data inside the backticks:
    `<h1>${headingContent}</h1>
     <img src="${imgUrl}" alt="${imgAlt}">
     <p>${bodyText}</p>`
    Assign this content to to your HTML-container that will
    be dynamically loaded (you already got the reference to
    this container before you started the function handleSelection) */

}

for (let i = 0; i < btnlist.length; i++) {
    btnlist[i].addEventListener("click", contenthandler);
}
window.addEventListener("click", contenthandler);
